# Generated by Django 5.1.4 on 2024-12-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='slug',
            field=models.SlugField(blank=True, max_length=155, unique=True),
        ),
    ]
