# Generated by Django 5.1.3 on 2024-11-24 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_popularity_alter_product_category_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
